### ISSUE TITLE
Design conventions

### ISSUE THREAD

**Issue by lacpe** [lacpe/soar-project#1]
Set some design conventions that will guide us through the designing of the UI:
- [ ] Color palette (highlighted/selected, unselected, disabled, and background - 1 or 2 of each)
- [ ] Basic shape language (are we rounding our rectangles, for example)
- [ ] Review structure and decide if pages need to be added/removed/changed

**Comment by TarceBoii** [comment]
![Capture d'écran_20230103_162834](https://github.com/user-attachments/assets/6d4361e7-f888-4956-8c97-eb9e6b6084f7)
